# initial schema
# Revision ID: 186c211a3eca
# Revises: None
# Create Date: 2026-07-26 14:12:12.831245

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186c211a3eca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('icon_name', sa.String(length=100), nullable=False),
    sa.Column('doctor_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('doctors',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('specialization', sa.String(length=200), nullable=False),
    sa.Column('room_no', sa.String(length=20), nullable=False),
    sa.Column('consultation_fee', sa.Float(), nullable=False),
    sa.Column('available_days', sa.JSON(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('Available', 'In_Surgery', 'On_Leave', 'Busy', name='doctor_status'), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_master',
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('Pharmaceuticals', 'Surgical_Supplies', 'Consumables', 'Lab_Reagents', 'Medical_Equipment', 'General_Store', name='item_category'), nullable=False),
    sa.Column('sub_category', sa.String(length=150), nullable=True),
    sa.Column('unit', sa.Enum('Box', 'Strip', 'Bottle', 'Vial', 'Piece', 'Pack', 'Roll', 'Set', name='item_unit'), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('hsn_code', sa.String(length=50), nullable=True),
    sa.Column('gst_percentage', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('max_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='item_status'), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_master_item_code'), 'item_master', ['item_code'], unique=True)
    op.create_table('patients',
    sa.Column('uhid', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.Enum('A_pos', 'A_neg', 'B_pos', 'B_neg', 'AB_pos', 'AB_neg', 'O_pos', 'O_neg', name='blood_group'), nullable=False),
    sa.Column('marital_status', sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='marital_status'), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alt_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('aadhaar', sa.String(length=20), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=False),
    sa.Column('emergency_relationship', sa.String(length=100), nullable=False),
    sa.Column('emergency_phone', sa.String(length=20), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('existing_diseases', sa.Text(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=150), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Admitted', 'Discharged', name='patient_status'), nullable=False),
    sa.Column('registration_date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_uhid'), 'patients', ['uhid'], unique=True)
    op.create_table('queue_items',
    sa.Column('token_number', sa.String(length=20), nullable=False),
    sa.Column('patient_uhid', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('Waiting', 'In_Consultation', 'Completed', 'On_Hold', 'Skipped', name='queue_status'), nullable=False),
    sa.Column('waiting_time_minutes', sa.Integer(), nullable=False),
    sa.Column('time_issued', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_activity',
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('activity', sa.String(length=200), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('Completed', 'Pending', 'Approved', 'In_Progress', 'Alert', name='store_activity_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('reception', 'doctor', 'nurse', 'lab', 'pharmacy', 'admin', 'patient', 'store', name='user_role'), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.Enum('Net_15', 'Net_30', 'Net_60', 'Advance', 'COD', name='payment_terms'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='vendor_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    op.create_table('appointments',
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('patient_uhid', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_mobile', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('doctor_name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time_slot', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Scheduled', 'Completed', 'Rescheduled', 'Cancelled', 'In_Progress', name='appointment_status'), nullable=False),
    sa.Column('created_date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_items',
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('mfg_date', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('expired_quantity', sa.Integer(), nullable=False),
    sa.Column('days_to_expiry', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Expired', 'Near_Expiry', 'Normal', name='batch_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beds',
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('ward', sa.Enum('General_Ward', 'ICU', 'Deluxe_Private', 'Semi_Private', 'Surgical_Ward', name='ward_type'), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Occupied', 'Reserved', 'Cleaning', name='bed_status'), nullable=False),
    sa.Column('current_patient_id', sa.String(length=36), nullable=True),
    sa.Column('current_patient_uhid', sa.String(length=50), nullable=True),
    sa.Column('current_patient_name', sa.String(length=200), nullable=True),
    sa.Column('admitted_date', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_number')
    )
    op.create_table('emergency_contacts',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_uhid', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Enum('Primary', 'Secondary', name='contact_priority'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('info', 'warning', 'success', name='notification_type'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('purchase_date', sa.String(length=20), nullable=False),
    sa.Column('expected_delivery', sa.String(length=20), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('total_discount', sa.Float(), nullable=False),
    sa.Column('total_gst', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Pending', 'Approved', 'Rejected', 'Fulfilled', name='po_status'), nullable=False),
    sa.Column('created_date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('stock_adjustment',
    sa.Column('adjustment_number', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('Damage', 'Lost', 'Expired', 'Manual_Correction', name='adjustment_type'), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('adjusted_quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_adjustment_adjustment_number'), 'stock_adjustment', ['adjustment_number'], unique=True)
    op.create_table('stock_inward',
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('warehouse', sa.String(length=150), nullable=True),
    sa.Column('received_by', sa.String(length=150), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_outward',
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('ward', sa.String(length=150), nullable=True),
    sa.Column('lab', sa.String(length=150), nullable=True),
    sa.Column('pharmacy', sa.String(length=150), nullable=True),
    sa.Column('operation_theatre', sa.String(length=150), nullable=True),
    sa.Column('doctor', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.String(length=150), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transfer',
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'In_Transit', 'Completed', 'Cancelled', name='transfer_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_transfer_number'), 'stock_transfer', ['transfer_number'], unique=True)
    op.create_table('walkin_tokens',
    sa.Column('token_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('patient_uhid', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=False),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=False),
    sa.Column('issue_time', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('Waiting', 'In_Consultation', 'Completed', 'Skipped', name='walkin_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_number')
    )
    op.create_table('goods_receipts',
    sa.Column('grn_number', sa.String(length=50), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('received_date', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Received', 'Verified', 'Completed', name='grn_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_grn_number'), 'goods_receipts', ['grn_number'], unique=True)
    op.create_table('ipd_admissions',
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('patient_uhid', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('ward', sa.Enum('General_Ward', 'ICU', 'Deluxe_Private', 'Semi_Private', 'Surgical_Ward', name='ipd_ward_type'), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('bed_id', sa.String(length=36), nullable=True),
    sa.Column('admission_date', sa.String(length=20), nullable=False),
    sa.Column('attending_doctor', sa.String(length=150), nullable=False),
    sa.Column('admission_reason', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=150), nullable=False),
    sa.Column('insurance_provider', sa.String(length=150), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Admitted', 'Discharged', 'Transferred', name='ipd_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('po_items',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grn_items',
    sa.Column('goods_receipt_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('accepted_quantity', sa.Integer(), nullable=False),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grn_items')
    op.drop_table('po_items')
    op.drop_table('ipd_admissions')
    op.drop_index(op.f('ix_goods_receipts_grn_number'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_table('walkin_tokens')
    op.drop_index(op.f('ix_stock_transfer_transfer_number'), table_name='stock_transfer')
    op.drop_table('stock_transfer')
    op.drop_table('stock_outward')
    op.drop_table('stock_inward')
    op.drop_index(op.f('ix_stock_adjustment_adjustment_number'), table_name='stock_adjustment')
    op.drop_table('stock_adjustment')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('notifications')
    op.drop_table('emergency_contacts')
    op.drop_table('beds')
    op.drop_table('batch_items')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('store_activity')
    op.drop_table('queue_items')
    op.drop_index(op.f('ix_patients_uhid'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_item_master_item_code'), table_name='item_master')
    op.drop_table('item_master')
    op.drop_table('doctors')
    op.drop_table('departments')
    # ### end Alembic commands ###
